# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [4]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [5]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [6]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[8, 3, 8, 3],
         [9, 3, 4, 4],
         [3, 2, 7, 7]],
 
        [[8, 8, 7, 3],
         [8, 2, 1, 6],
         [1, 6, 9, 1]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [7]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [8]:
c = a-b
c

array([20, 29, 38, 47])

In [9]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [10]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [11]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
a[2:5]

array([ 4,  9, 16])

In [13]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [14]:
b = np.random.randint(1,100,(4,4))

In [15]:
b

array([[ 1, 31, 11, 30],
       [67, 12, 12, 24],
       [66, 28, 40, 29],
       [93, 93, 30, 36]])

In [16]:
# Guess the output
print(b[2,3])
print(b[0,0])


29
1


In [17]:
b[0:3,1],b[:,1]

(array([31, 12, 28]), array([31, 12, 28, 93]))

In [18]:
b[1:3,:]

array([[67, 12, 12, 24],
       [66, 28, 40, 29]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [22]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-03 -0.198534 -0.241947  0.470381  1.433482
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113

In [23]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [24]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [25]:
#gives first five data
df.head()

A         B         C         D
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-03 -0.198534 -0.241947  0.470381  1.433482
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418

In [26]:
#gives last five data
df.tail()

A         B         C         D
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-03 -0.198534 -0.241947  0.470381  1.433482
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113

In [27]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
#gives summary for statistics
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.326657 -0.756213  0.032664 -0.190729
std    0.929991  0.695362  0.540741  1.183811
min   -1.727269 -2.027305 -0.701536 -2.045113
25%   -0.739158 -0.826586 -0.370869 -0.696577
50%   -0.261955 -0.691926  0.151467  0.004494
75%    0.059800 -0.322754  0.490977  0.292526
max    1.022414 -0.054948  0.535419  1.433482

In [29]:
#sort values for a particular column
df.sort_values(by='B')

A         B         C         D
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418
2014-01-03 -0.198534 -0.241947  0.470381  1.433482
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113

### Selection

In [30]:
df[['A','B']]

A         B
2014-01-01 -1.727269 -2.027305
2014-01-02 -0.325377 -0.829222
2014-01-03 -0.198534 -0.241947
2014-01-04  0.145912 -0.818678
2014-01-05  1.022414 -0.565175
2014-01-06 -0.877086 -0.054948

In [31]:
df[0:3]

A         B         C         D
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-03 -0.198534 -0.241947  0.470381  1.433482

In [32]:
# By label
df.loc[dates[0]]

A   -1.727269
B   -2.027305
C   -0.167448
D    0.040041
Name: 2014-01-01 00:00:00, dtype: float64

In [33]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01 -1.727269 -2.027305
2014-01-02 -0.325377 -0.829222
2014-01-03 -0.198534 -0.241947
2014-01-04  0.145912 -0.818678
2014-01-05  1.022414 -0.565175
2014-01-06 -0.877086 -0.054948

In [34]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.829222
2014-01-03 -0.241947
2014-01-04 -0.818678

In [35]:
# Fast access to scalar
df.at[dates[1],'B']

-0.82922207653822666

In [36]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113

### Boolean Indexing

In [37]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041
2014-01-02 -0.325377 -0.829222  0.497843  0.376688
2014-01-03 -0.198534 -0.241947  0.470381  1.433482
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113

### Setting

In [38]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [39]:
df_posA

A         B         C         D
2014-01-01  1.727269  2.027305  0.167448 -0.040041
2014-01-02  0.325377  0.829222 -0.497843 -0.376688
2014-01-03  0.198534  0.241947 -0.470381 -1.433482
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054
2014-01-05  1.022414 -0.565175  0.535419 -0.918418
2014-01-06  0.877086  0.054948  0.438676  2.045113

In [40]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [41]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [42]:
df['F'] = s1

In [43]:
df

A         B         C         D    F
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041  NaN
2014-01-02 -0.325377 -0.829222  0.497843  0.376688  1.0
2014-01-03 -0.198534 -0.241947  0.470381  1.433482  2.0
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054  3.0
2014-01-05  1.022414 -0.565175  0.535419 -0.918418  4.0
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113  5.0

### Missing Data

In [44]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [45]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [46]:
df1

A         B         C         D    F    E
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041  NaN  1.0
2014-01-02 -0.325377 -0.829222  0.497843  0.376688  1.0  1.0
2014-01-03 -0.198534 -0.241947  0.470381  1.433482  2.0  NaN
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054  3.0  NaN

In [47]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [48]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.326657 -0.756213  0.032664 -0.190729  3.000000
std    0.929991  0.695362  0.540741  1.183811  1.581139
min   -1.727269 -2.027305 -0.701536 -2.045113  1.000000
25%   -0.739158 -0.826586 -0.370869 -0.696577  2.000000
50%   -0.261955 -0.691926  0.151467  0.004494  3.000000
75%    0.059800 -0.322754  0.490977  0.292526  4.000000
max    1.022414 -0.054948  0.535419  1.433482  5.000000

In [49]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.326657
 B   -0.756213
 C    0.032664
 D   -0.190729
 F    3.000000
 dtype: float64, 2014-01-01   -0.970495
 2014-01-02    0.143986
 2014-01-03    0.692676
 2014-01-04    0.318929
 2014-01-05    0.814848
 2014-01-06    0.316835
 Freq: D, dtype: float64)

### Applying functions

In [50]:
df

A         B         C         D    F
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041  NaN
2014-01-02 -0.325377 -0.829222  0.497843  0.376688  1.0
2014-01-03 -0.198534 -0.241947  0.470381  1.433482  2.0
2014-01-04  0.145912 -0.818678 -0.701536 -0.031054  3.0
2014-01-05  1.022414 -0.565175  0.535419 -0.918418  4.0
2014-01-06 -0.877086 -0.054948 -0.438676 -2.045113  5.0

In [51]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01 -1.727269 -2.027305 -0.167448  0.040041   NaN
2014-01-02 -2.052646 -2.856527  0.330396  0.416729   1.0
2014-01-03 -2.251180 -3.098475  0.800776  1.850210   3.0
2014-01-04 -2.105268 -3.917152  0.099240  1.819156   6.0
2014-01-05 -1.082855 -4.482327  0.634659  0.900738  10.0
2014-01-06 -1.959940 -4.537275  0.195983 -1.144376  15.0

In [52]:
df.apply(lambda x: x.max() - x.min())

A    2.749683
B    1.972357
C    1.236955
D    3.478595
F    4.000000
dtype: float64

In [53]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [54]:
np.random.randn(10,4)

array([[-0.02602354,  0.7762187 ,  1.84718195, -0.36705401],
       [-0.07672341, -0.08872914, -0.22442646,  0.99979203],
       [-0.89127324,  0.14771284,  0.24597075, -1.62172508],
       [-1.02461795, -0.5575906 , -0.71839877,  1.35521216],
       [-1.08824245, -0.478853  , -0.30235982,  0.13884769],
       [ 0.68597085, -1.64639911, -1.35455088,  2.42857175],
       [ 1.05464732,  1.17738612, -1.01553127, -0.60927373],
       [ 0.66689252,  1.58426038,  0.12566413, -0.06528877],
       [ 1.877188  , -0.33080127,  1.17029473, -0.02556582],
       [ 0.35154283,  0.55064013, -0.68727403,  1.23211434]])

In [55]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0  0.088110  0.143143 -0.785410 -0.953955
1  1.399289  0.819126  0.265055  1.040660
2 -0.198989  0.440702  0.078867  0.470438
3 -0.095972  0.875761 -0.965185 -0.698537
4 -0.986341  1.732667 -0.898746  0.918371
5  0.411649 -1.196529 -0.056169  1.417357
6 -0.125345  0.458627  0.030790  0.830669
7 -0.530541  0.242076 -0.411740  0.579627
8 -0.488200 -0.021381  0.468421  0.978598
9  1.404029  0.006128 -1.163153  1.060954

In [56]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0  0.088110  0.143143 -0.785410 -0.953955
 1  1.399289  0.819126  0.265055  1.040660
 2 -0.198989  0.440702  0.078867  0.470438,
           0         1         2         3
 3 -0.095972  0.875761 -0.965185 -0.698537
 4 -0.986341  1.732667 -0.898746  0.918371
 5  0.411649 -1.196529 -0.056169  1.417357
 6 -0.125345  0.458627  0.030790  0.830669,
           0         1         2         3
 7 -0.530541  0.242076 -0.411740  0.579627
 8 -0.488200 -0.021381  0.468421  0.978598
 9  1.404029  0.006128 -1.163153  1.060954]

In [57]:
pd.concat(pieces)

0         1         2         3
0  0.088110  0.143143 -0.785410 -0.953955
1  1.399289  0.819126  0.265055  1.040660
2 -0.198989  0.440702  0.078867  0.470438
3 -0.095972  0.875761 -0.965185 -0.698537
4 -0.986341  1.732667 -0.898746  0.918371
5  0.411649 -1.196529 -0.056169  1.417357
6 -0.125345  0.458627  0.030790  0.830669
7 -0.530541  0.242076 -0.411740  0.579627
8 -0.488200 -0.021381  0.468421  0.978598
9  1.404029  0.006128 -1.163153  1.060954

In [58]:
# Also can "Join" and "Append"
df

0         1         2         3
0  0.088110  0.143143 -0.785410 -0.953955
1  1.399289  0.819126  0.265055  1.040660
2 -0.198989  0.440702  0.078867  0.470438
3 -0.095972  0.875761 -0.965185 -0.698537
4 -0.986341  1.732667 -0.898746  0.918371
5  0.411649 -1.196529 -0.056169  1.417357
6 -0.125345  0.458627  0.030790  0.830669
7 -0.530541  0.242076 -0.411740  0.579627
8 -0.488200 -0.021381  0.468421  0.978598
9  1.404029  0.006128 -1.163153  1.060954

### Grouping


In [59]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [60]:
df

A      B         C         D
0  foo    one  0.329802 -0.391774
1  bar    one  0.254804 -0.931513
2  foo    two  0.620658  0.467117
3  bar  three  0.003695 -0.632015
4  foo    two -0.030093  1.264237
5  bar    two -1.666711 -1.090993
6  foo    one  0.944604  2.158189
7  foo  three  1.627313 -2.027652

In [61]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    0.254804 -0.931513
    three  0.003695 -0.632015
    two   -1.666711 -1.090993
foo one    1.274407  1.766415
    three  1.627313 -2.027652
    two    0.590564  1.731354

### Reshaping

In [62]:
# You can also stack or unstack levels

In [63]:
a = df.groupby(['A','B']).sum()

In [64]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  0.254804  0.003695 -1.666711 -0.931513 -0.632015 -1.090993
foo  0.637203  1.627313  0.295282  0.883208 -2.027652  0.865677

### Time Series


In [65]:
import pandas as pd
import numpy as np

In [66]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [67]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [68]:
ts

2014-01-01 00:00:00    379
2014-01-01 00:00:01    493
2014-01-01 00:00:02    115
2014-01-01 00:00:03     73
2014-01-01 00:00:04    207
2014-01-01 00:00:05    103
2014-01-01 00:00:06    137
2014-01-01 00:00:07    275
2014-01-01 00:00:08    233
2014-01-01 00:00:09    348
2014-01-01 00:00:10     77
2014-01-01 00:00:11    206
2014-01-01 00:00:12     72
2014-01-01 00:00:13    443
2014-01-01 00:00:14    103
2014-01-01 00:00:15    442
2014-01-01 00:00:16     70
2014-01-01 00:00:17    409
2014-01-01 00:00:18    492
2014-01-01 00:00:19    228
2014-01-01 00:00:20    398
2014-01-01 00:00:21    441
2014-01-01 00:00:22    453
2014-01-01 00:00:23    444
2014-01-01 00:00:24    447
2014-01-01 00:00:25    317
2014-01-01 00:00:26    176
2014-01-01 00:00:27     48
2014-01-01 00:00:28    289
2014-01-01 00:00:29    355
                      ... 
2014-01-01 00:01:10    163
2014-01-01 00:01:11     94
2014-01-01 00:01:12    287
2014-01-01 00:01:13    444
2014-01-01 00:01:14    436
2014-01-01 00:01:15    135
2

In [69]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    263.683333
2014-01-01 00:01:00    221.025000
Freq: T, dtype: float64

In [70]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-70-5c9240a56f62>, line 2)

### Plotting


In [71]:
ts.plot()

In [72]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [73]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [74]:
# Pandas plot function will print with labels as default

In [75]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas