# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [3]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [4]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [5]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[5, 9, 8, 2],
         [7, 1, 9, 5],
         [5, 1, 1, 8]],
 
        [[5, 6, 4, 1],
         [3, 5, 6, 6],
         [6, 8, 9, 1]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [6]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [7]:
c = a-b
c

array([20, 29, 38, 47])

In [8]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [9]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [10]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [12]:
b = np.random.randint(1,100,(4,4))

In [13]:
b

array([[ 8, 42, 10,  8],
       [15, 59, 56, 51],
       [12, 31, 54, 17],
       [31, 99, 55, 70]])

In [14]:
# Guess the output
print(b[2,3])
print(b[0,0])


17
8


In [15]:
b[0:3,1],b[:,1]

(array([42, 59, 31]), array([42, 59, 31, 99]))

In [16]:
b[1:3,:]

array([[15, 59, 56, 51],
       [12, 31, 54, 17]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [20]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  1.045621  0.047362  0.240087  1.006041
2014-01-02 -0.933520  0.481525  0.124788 -0.179267
2014-01-03  1.195735  1.042277  2.861142 -0.014861
2014-01-04  1.764974 -0.858765 -1.319830 -0.236557
2014-01-05 -1.312326  1.997776 -1.520079 -1.038787
2014-01-06  0.122961  0.172789  0.202631 -0.133204

In [21]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [22]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [24]:
#gives first five data
df.head()

A         B         C         D
2014-01-01  1.045621  0.047362  0.240087  1.006041
2014-01-02 -0.933520  0.481525  0.124788 -0.179267
2014-01-03  1.195735  1.042277  2.861142 -0.014861
2014-01-04  1.764974 -0.858765 -1.319830 -0.236557
2014-01-05 -1.312326  1.997776 -1.520079 -1.038787

In [25]:
#gives last five data
df.tail()

A         B         C         D
2014-01-02 -0.933520  0.481525  0.124788 -0.179267
2014-01-03  1.195735  1.042277  2.861142 -0.014861
2014-01-04  1.764974 -0.858765 -1.319830 -0.236557
2014-01-05 -1.312326  1.997776 -1.520079 -1.038787
2014-01-06  0.122961  0.172789  0.202631 -0.133204

In [26]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
#gives summary for statistics
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.313908  0.480494  0.098123 -0.099439
std    1.237400  0.968881  1.568135  0.653900
min   -1.312326 -0.858765 -1.520079 -1.038787
25%   -0.669400  0.078719 -0.958675 -0.222235
50%    0.584291  0.327157  0.163709 -0.156236
75%    1.158207  0.902089  0.230723 -0.044447
max    1.764974  1.997776  2.861142  1.006041

In [30]:
#sort values for a particular column
df.sort_values(by='B')

A         B         C         D
2014-01-04  1.764974 -0.858765 -1.319830 -0.236557
2014-01-01  1.045621  0.047362  0.240087  1.006041
2014-01-06  0.122961  0.172789  0.202631 -0.133204
2014-01-02 -0.933520  0.481525  0.124788 -0.179267
2014-01-03  1.195735  1.042277  2.861142 -0.014861
2014-01-05 -1.312326  1.997776 -1.520079 -1.038787

### Selection

In [ ]:
df[['A','B']]

In [ ]:
df[0:3]

In [ ]:
# By label
df.loc[dates[0]]

In [ ]:
# multi-axis by label
df.loc[:,['A','B']]

In [ ]:
# Date Range
df.loc['20140102':'20140104',['B']]

In [ ]:
# Fast access to scalar
df.at[dates[1],'B']

In [ ]:
# iloc provides integer locations similar to np style
df.iloc[3:]

### Boolean Indexing

In [ ]:
df[df.A < 0] # Basically a 'where' operation

### Setting

In [ ]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [ ]:
df_posA

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes

### Applying functions

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Merge

In [ ]:
np.random.randn(10,4)

In [ ]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

In [ ]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas